### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by ljc3084** [ds4owd-001/project-ljc3084#4]
Hello @mianzg  

I've made improvements to my project again. I've been able to work on the issues you raised earlier.
I am currently stuck at writing the processed file into the data/processed file path.

I've tried two codes that are both returning errors.

write.csv(here::here("data/raw/processed_borehole_data.csv"))
write.csv(processed_borehole_data, file = "data/processed/processed_borehole_data.csv")

Any help is welcome

**Comment by ljc3084** [comment]
Hello @mianzg here is my final one before final tounches.
Any guidance is very welcome

**Comment by ljc3084** [comment]
Hello @mianzg @larnsce I've pushed my final project report. Thank you for the guidance, it has been a good experience and a lot learned to use in my career.

**Comment by mianzg** [comment]
@ljc3084 Congratulations! We will start to review the project and provide feedbacks in the following weeks. Thanks for participating the course and submitting the project.
