### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by mianzg** [ds4owd-001/project-ljc3084#5]
@ljc3084  Congrats again on accomplishing your capstone project! We are happy that you went through the course with us and applied the skills in the project.

I am reviewing your project on "Borehole Data Analysis for Clean Water Access". Note that my review does not have any assessment on the writing content of the report, but I did enjoy reading it and learnt new stuff.

Please find the detailed feedback in the next section.

**Comment by mianzg** [comment]
@ljc3084 
You completed most of the items in the [Required Items](https://ds4owd-001.github.io/website/project/#required-items). Great job!

We would encourage you to improve on the missing items:
**Technical**
You have a good webpage of the report where the yaml header is correct and hides the warning messages. However,
1. Each data visualisation has a label defined in the code-chunk options, and each data visualisation is cross-referenced in the narrative using the defined label from the code-chunk options. What you have now should go into "caption" instead of "label", and you did not use cross-reference for the figures in the report. For example, the following figure code chunk 

The histogram below showing the distribution of well depth across two districts.
```
#| label: Histogram showing distribution of well_depth per district

ggplot(data = district_column,
       mapping = aes(x = well_depth,
                     fill = district)) +
  geom_histogram()+
  xlab("Borehole Depth(m)")+
  ylab("No. of Boreholes")+
labs(title = "Borehole population served summary, data from two districts")
```
could be improved to:

The histogram @fig-welldepth-hist showing the distribution of well depth across two districts.
```
#| label: fig-welldepth-hist
#| fig-cap: Histogram showing distribution of well_depth per district

ggplot(data = district_column,
       mapping = aes(x = well_depth,
                     fill = district)) +
  geom_histogram()+
  xlab("Borehole Depth(m)")+
  ylab("No. of Boreholes")+
labs(title = "Borehole population served summary, data from two districts")
```

2. The table label must start with the `tbl-` prefix, so you need to change `#| label: tbl_bhr_summary` to `#| label: tbl-bhr_summary` in line 171

**Data**
Well-documented dictionary csvfile for data understanding. However, your readme file is missing information

**Intellectual**
All sections are written concisely and the figures are provided with good explanations. The third figure "Boreholes repaired by quarter" might be better plotted with x axis as the year and the fill as the quarter. Why? Based on your text, you would like to compare which quarter where majority of boreholes were repaired within a year, then you have a bar for each year that is divided into four-colour bars to do the comparison.

**Comment by mianzg** [comment]
@ljc3084 Furthermore, we would like to have your project and data turning into an openwashdata data package! That means, we will develop an R data package that you will be an author. You and others can directly use a tidy version of the data in R later. Please let us know if you are interested in this! @margauxgo @larnsce

**Comment by ljc3084** [comment]
Hello @mianzg thank you for all the suggestions about the data. Looking through my project again, alot of your suggestions do make sense, so I have adopted them. The one I appreciate the most is the one relating to the column chart which is my third figure.

Thank you for considering my project and data for the openwash data package too.

**Comment by mianzg** [comment]
> Hello @mianzg thank you for all the suggestions about the data. Looking through my project again, alot of your suggestions do make sense, so I have adopted them. The one I appreciate the most is the one relating to the column chart which is my third figure.
> 
> Thank you for considering my project and data for the openwash data package too.

@ljc3084 This is great to hear! I have added this to our data list, and we will start to develop the package together. For your next step, could you support us by updating this README file: https://github.com/ds4owd-001/project-ljc3084/blob/master/data/processed/README.md

I saw you have filled in most information, and I would appreciate if you provide more background by updating it. Thanks!

**Comment by ljc3084** [comment]
Hello @mianzg I've made updates to the ReadMe document as requested.

**Comment by margauxgo** [comment]
Hi @ljc3084 I am currently working on developing a data package for your data and would be happy if you could add the raw data to the data-raw folder of [ugabore](https://github.com/openwashdata/ugabore)! I have already invited you as a collaborator there.

**Comment by ljc3084** [comment]
Hello @margauxgo I've added the borehole raw data as requested. Thanks
